<a href="https://colab.research.google.com/github/JoDeMiro/Ember/blob/main/Autograd_mxnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://www.youtube.com/watch?v=fRf4l5qaX1M

## Automatic Differentiation

### Import `autograd` and create variable

In [ ]:
!pip install mxnet

     |████████████████████████████████| 46.9MB 91kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [ ]:
from mxnet import autograd, nd

In [ ]:
x = nd.arange(4).reshape((4,1))

print(x)


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>


## Attach gradient to `x`

- It allocates memory to store its gradient, which has the same shapes as `x`
- It also tell the system that we need to compute its gradient.

In [ ]:
x.attach_grad()
x.grad


[[0.]
 [0.]
 [0.]
 [0.]]
<NDArray 4x1 @cpu(0)>

## Foreward

Now compute $ y = 2x^\mathsf{T}x $

by placing code inside a with autograd.record(): block. MXNet will build the according computation graph.

In [ ]:
with autograd.record():
  y = 2 * nd.dot(x.T, x)

y


[[28.]]
<NDArray 1x1 @cpu(0)>

## Backward

In [ ]:
y.backward()

## Get the gradient

Given $ y = 2x^\mathsf{T}x $, we know

Partial firt order deivative	: $$\frac{\partial y}{\partial x} = 4x $$

Now verify the result:

In [ ]:
print((x.grad - 4 * x).norm().asscalar() == 0)
print(x.grad)

True

[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>


## Backward on non-scalar

`y.backward()` equals to `y.sum().backward()`

In [ ]:
with autograd.record():
  y = 2 * x * x

print(y.shape)

y.backward()

print(x.grad)

(4, 1)

[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>


Foyltatni

https://youtu.be/fRf4l5qaX1M?t=322

## Latex

https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd